# Example for using the keymap-drawer ZMK user config workflow
name: Draw ZMK keymaps
on:
  workflow_dispatch:  # can be triggered manually
  push:               # automatically run on changes to following paths
    paths:
      - "config/*.keymap"
      - "keymap-drawer/config.yaml"
      - ".github/workflows/keymap-drawer.yml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write  # allow workflow to commit to the repo
    with:
      keymap_patterns: "config/le_jlwffre.keymap config/elchibre.keymap"  # path to the keymaps to parse
      config_path: "keymap-drawer/config.yaml"  # config file, ignored if not exists
      output_folder: "keymap-drawer"            # path to save produced SVG and keymap YAML files
      draw_args: "le_jlwffre:'-d keymap-drawer/le_jlwffre-layouts.dtsi' elchibre:'-d keymap-drawer/elchibre-layouts.dtsi'"
      fail_on_error: true
